[package]
name = "ckb-ssri-executor-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
serde_json = { version = "1" }
serde = { version = "1", features = ["derive"] }
console_error_panic_hook = { version = "0.1.6", optional = true }
wasm-bindgen-futures = "0.4"
log = "0.4"
wasm-logger = "0.2"
serde-wasm-bindgen = "0.6.5"

ckb-types = "0.116.1"
ckb-jsonrpc-types = "0.116.1"
ckb-vm = "=0.24.9"
ckb-hash = "0.116.1"


hex = { version = "0.4.3", features = ["serde"] }
web-sys = { version = "0.3.77", features = ["XmlHttpRequest", "Window", "Request", "RequestInit", "RequestMode", "Response", "TextEncoder"] }
getrandom = { version = "0.2", features = ["js"] }

[dependencies.schemars]
version = "0.8.19"
package = "ckb_schemars"


[features]
default = ["console_error_panic_hook"]

# [profile.release]
# # Tell `rustc` to optimize for small code size.
# opt-level = "s"
