name: Build, lint and test

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 26
      - uses: pnpm/action-setup@v6

      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build:all
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test:ci
